# Cloud Build configuration: build Docker image, push to Artifact Registry (us-central1),
# and create a Cloud Deploy release that will run the delivery pipeline to deploy to Cloud Run
#
# Usage:
#  gcloud builds submit --config cloudbuild.yaml .
# To run build+deploy (create a Cloud Deploy release):
#  gcloud builds submit --config cloudbuild.yaml --substitutions=_SERVICE="romans-click-count",_PIPELINE="clickcount-pipeline",_DEPLOY_TO_CLOUD_DEPLOY=true
#
# Preconditions:
# - Artifact Registry repository "clickcountdemo" exists in us-central1.
# - Cloud Deploy delivery pipeline "clickcount-pipeline" exists and has targets "staging" and "production", or set _PIPELINE to your pipeline name.
# - Cloud Build service account has roles/artifactregistry.writer and roles/clouddeploy.releasemanager, and permission to update Cloud Run if needed.

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE: "romans-click-count"
  _REGION: "us-central1"
  _REPOSITORY: "clickcountdemo"
  _DEPLOY_TO_CLOUD_DEPLOY: "true"
  _PIPELINE: "clickcount-pipeline"
  _RELEASE: ""  # optional; defaults to release-$BUILD_ID when empty

steps:
# 1) Configure Docker auth for Artifact Registry (region-specific)
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args:
  - "-c"
  - |
    set -e
    echo "Configuring Docker authentication for Artifact Registry in region: ${_REGION}"
    gcloud auth configure-docker "${_REGION}-docker.pkg.dev" --quiet

# 2) Build the Docker image and tag it for Artifact Registry
- name: "gcr.io/cloud-builders/docker"
  args:
  - "build"
  - "-t"
  # MODIFIED: Use $BUILD_ID instead of $SHORT_SHA
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID"
  - "."

# 3) Push the image to Artifact Registry
- name: "gcr.io/cloud-builders/docker"
  args:
  - "push"
  # MODIFIED: Use $BUILD_ID instead of $SHORT_SHA
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID"

# 4) Optionally create a Cloud Deploy release
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args:
  - "-c"
  - |
    set -e
    if [ "${_DEPLOY_TO_CLOUD_DEPLOY}" = "true" ]; then
      # MODIFIED: Use $BUILD_ID instead of $SHORT_SHA
      _IMAGE="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID"
      # MODIFIED: Use $BUILD_ID as the fallback instead of $SHORT_SHA
      _RELEASE_NAME="${_RELEASE:-release-$BUILD_ID}"
      echo "Creating Cloud Deploy release '${_RELEASE_NAME}' for delivery pipeline '${_PIPELINE}' using image: ${_IMAGE}"
      gcloud deploy releases create "${_RELEASE_NAME}" \
        --delivery-pipeline="${_PIPELINE}" \
        --region="${_REGION}" \
        --images="${_SERVICE}=${_IMAGE}"
      echo "Cloud Deploy release created successfully."
    else
      echo "Skipping Cloud Deploy release creation"
    fi

images:
# MODIFIED: Use $BUILD_ID instead of $SHORT_SHA
- "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID"

timeout: "1200s"