# Cloud Build configuration
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE: "romans-click-count"
  _REGION: "us-central1"
  _REPOSITORY: "clickcountdemo"
  _DEPLOY_TO_CLOUD_DEPLOY: "true"
  _PIPELINE: "clickcount-pipeline"
  _RELEASE: ""  # optional; defaults to release-$BUILD_ID when empty

steps:
# 1) Configure Docker auth
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args:
  - "-c"
  - |
    set -e
    echo "Configuring Docker authentication for Artifact Registry in region: ${_REGION}"
    gcloud auth configure-docker "${_REGION}-docker.pkg.dev" --quiet

# 2) Build the Docker image
- name: "gcr.io/cloud-builders/docker"
  args:
  - "build"
  - "-t"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID"
  - "."

# 3) Push the image
- name: "gcr.io/cloud-builders/docker"
  args:
  - "push"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID"

# 4) Optionally create a Cloud Deploy release
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  # Pass built-in variables ($PROJECT_ID, $BUILD_ID) to the script
  env:
  - 'PROJECT_ID=${PROJECT_ID}'
  - 'BUILD_ID=${BUILD_ID}'
  - '_IMAGE=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID'
  entrypoint: "bash"
  args:
  - "-c"
  - |
    set -e 
    if [ "${_DEPLOY_TO_CLOUD_DEPLOY}" = "true" ]; then
      
      _RELEASE_NAME="${RELEASE:-release-$BUILD_ID}"
      
      echo "Creating Cloud Deploy , bid '$BUILD_ID' release '${_RELEASE_NAME}' for delivery pipeline '${_PIPELINE}' using image: $_IMAGE"
      
      # Use the script variables (without '_') here
      gcloud deploy releases create "${_RELEASE_NAME}" \
        --delivery-pipeline="${_PIPELINE}" \
        --region="${_REGION}" \
        --images="${_SERVICE}=${IMAGE}"
      echo "Cloud Deploy release created successfully."
    else
      echo "Skipping Cloud Deploy release creation"
    fi

# This 'images' block is substituted by Cloud Build before runtime
images:
- "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID"

timeout: "1200s"