# Cloud Build configuration: build Docker image, push to Artifact Registry (us-central1),
# and create a Cloud Deploy release that will run the delivery pipeline to deploy to Cloud Run

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE: "romans-click-count"
  _REGION: "us-central1"
  _REPOSITORY: "clickcountdemo"
  _DEPLOY_TO_CLOUD_DEPLOY: "true"
  _PIPELINE: "clickcount-pipeline"
  _RELEASE: ""  # optional; defaults to release-$BUILD_ID when empty

steps:
# 1) Configure Docker auth for Artifact Registry (region-specific)
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args:
  - "-c"
  - |
    set -e
    # $_REGION works here because it's in an 'args' block, not 'entrypoint'
    echo "Configuring Docker authentication for Artifact Registry in region: ${_REGION}"
    gcloud auth configure-docker "${_REGION}-docker.pkg.dev" --quiet

# 2) Build the Docker image and tag it for Artifact Registry
- name: "gcr.io/cloud-builders/docker"
  args:
  - "build"
  - "-t"
  # $PROJECT_ID and $BUILD_ID work here because it's an 'args' block
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID"
  - "."

# 3) Push the image to Artifact Registry
- name: "gcr.io/cloud-builders/docker"
  args:
  - "push"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID"

# 4) Optionally create a Cloud Deploy release
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  # *** FIX 1: Add 'env' block to pass in built-in variables ***
  env:
  - 'PROJECT_ID=${PROJECT_ID}'
  - 'BUILD_ID=${BUILD_ID}'
  entrypoint: "bash"
  args:
  - "-c"
  - |
    set -e
    # *** FIX 2: Refer to variables *without* the '_' prefix ***
    # User substitutions (like _REGION) become $REGION.
    # Built-in variables (like $PROJECT_ID) are passed from the 'env' block.
    
    if [ "${DEPLOY_TO_CLOUD_DEPLOY}" = "true" ]; then
      _IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:$BUILD_ID"
      _RELEASE_NAME="${RELEASE:-release-$BUILD_ID}"
      
      echo "Creating Cloud Deploy release '${_RELEASE_NAME}' for delivery pipeline '${PIPELINE}' using image: ${_IMAGE}"
      
      gcloud deploy releases create "${_RELEASE_NAME}" \
        --delivery-pipeline="${PIPELINE}" \
        --region="${REGION}" \
        --images="${SERVICE}=${_IMAGE}"
      echo "Cloud Deploy release created successfully."
    else
      echo "Skipping Cloud Deploy release creation"
    fi

images:
- "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID"

timeout: "1200s"