options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE: "romans-click-count"
  _REGION: "us-central1"
  _REPOSITORY: "clickcountdemo"
  _PIPELINE: "clickcount-pipeline"
  # Default to SHA (for staging)
  # You MUST override this in the Production Trigger to be "${TAG_NAME}"
  _IMAGE_TAG: "${SHORT_SHA}" 
  _IMAGE: "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE}:${_IMAGE_TAG}"
  

steps:
# 1) Configure Docker auth
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args:
  - "-c"
  - |
    gcloud auth configure-docker "${_REGION}-docker.pkg.dev" --quiet

# 2) Build
# Uses _IMAGE_TAG (which is either SHA or TAG_NAME depending on the trigger)
- name: "gcr.io/cloud-builders/docker"
  args:
  - "build"
  - "-t"
  - "${_IMAGE}"
  - "."

# 3) Push
- name: "gcr.io/cloud-builders/docker"
  args:
  - "push"
  - "${_IMAGE}"

# 4) Create Release
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args:
  - "-c"
  - |
    set -e
    
    # We check TAG_NAME to decide the RELEASE NAME and logic
    if [ -n "$TAG_NAME" ]; then
      echo "Git Tag detected: $TAG_NAME. Creating Production Release for image ${_IMAGE}"
      
      # Release name based on Tag (e.g., rel-v1.0.0)
      gcloud deploy releases create "rel-${TAG_NAME}" \
        --delivery-pipeline="${_PIPELINE}" \
        --region="${_REGION}" \
        --images="${_SERVICE}=${_IMAGE}" \ 
        --skaffold-version="2.16.0"
    else
      echo "No Git Tag detected. Creating Staging Release for image ${_IMAGE}"
      
      # Release name based on SHA (e.g., sha-a1b2c3d)
      gcloud deploy releases create "sha-${SHORT_SHA}" \
        --delivery-pipeline="${_PIPELINE}" \
        --region="${_REGION}" \
        --images="${_SERVICE}=${_IMAGE}" \
        --skaffold-version="2.16.0" 
    fi

images:
- "${_IMAGE}"