options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE: "romans-click-count"
  _REGION: "us-central1"
  _REPOSITORY: "clickcountdemo"
  _PIPELINE: "clickcount-pipeline" # Must match metadata.name in clouddeploy.yaml
  _IMAGE: "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE}:${BUILD_ID}"
  _RELEASE_NAME: "rel-${SHORT_SHA}"

steps:
# 1) Configure Docker auth
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args:
  - "-c"
  - |
    gcloud auth configure-docker "${_REGION}-docker.pkg.dev" --quiet

# 2) Build the Docker image
- name: "gcr.io/cloud-builders/docker"
  args:
  - "build"
  - "-t"
  - "${_IMAGE}"
  - "."

# 3) Push the image
- name: "gcr.io/cloud-builders/docker"
  args:
  - "push"
  - "${_IMAGE}"

# 4) Create a Cloud Deploy release
# This triggers the rollout to the first target (Staging) automatically
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args:
  - "-c"
  - |
    echo "Creating Cloud Deploy release ${_RELEASE_NAME}..."
    gcloud deploy releases create "${_RELEASE_NAME}" \
      --delivery-pipeline="${_PIPELINE}" \
      --region="${_REGION}" \
      --images="${_SERVICE}=${_IMAGE}" \
      --skaffold-version="2.16.0" 

images:
- "${_IMAGE}"

timeout: "1200s"