apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: clickcount-pipeline
serialPipeline:
  stages:
  - targetId: staging
    profiles: [staging] # Matches skaffold profile
  - targetId: prod
    profiles: [prod]    # Matches skaffold profile

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: Staging Cloud Run Service
run:
  location: projects/romans-testing/locations/us-central1

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Production Cloud Run Service
requireApproval: true # <--- This enforces the manual button click
run:
  location: projects/romans-testing/locations/us-central1