apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: romans-click-count
build:
  artifacts:
    - image: romans-click-count
  googleCloudBuild: {}

# Default manifest (fallback)
manifests:
  kustomize:
    paths:
    - k8s/overlays/staging

deploy:
  cloudrun: {}

profiles:
  # The profile name must match the Target ID in Cloud Deploy
  - name: staging
    manifests:
      kustomize:
        paths:
        - k8s/overlays/staging

  - name: prod
    manifests:
      kustomize:
        paths:
        - k8s/overlays/prod