apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: romans-click-count
build:
  artifacts:
    - image: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE}:${BUILD_ID}
  googleCloudBuild: {} 
  
# --- ADDED MANIFESTS SECTION ---
manifests:
  rawYaml:
    - service.yaml # <-- Point to your Cloud Run service definition file

deploy:
  cloudrun: {} # This tells Skaffold to use the native Cloud Run deployer

profiles:
  - name: local
    build:
      local: {}
    deploy:
      # Optional: Add any local deployment config here, 
      # or remove the deploy block entirely for local runs.
      pass