apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: romans-click-count
build:
  artifacts:
    - image: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE}:${BUILD_ID}
  googleCloudBuild: {} 
  
manifests:
  rawYaml:
    - service.yaml 

deploy:
  cloudrun: {} 

profiles:
  
  - name: target-1 
    # It can be empty as it inherits the main build/deploy blocks
  
  
  - name: local
    build:
      local: {}